common:
  dataset: "vanjee"
  lid_topic: "/velodyne_points"
  imu_topic: "/imu_data"
  time_sync_en: false         # ONLY turn on when external time synchronization is really not possible

preprocess:
  lidar_type: 4                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 4 for Robotsense LiDAR,
  scan_line: 16
  blind: 0.10
  rangeMinX: -200
  rangeMaxX: 200
  rangeMinY: -5
  rangeMaxY: 10  #10
  rangeMinZ: -2.0
  rangeMaxZ: 5.0
  time_scale: 1e-3             # 兼容不同数据集的时间单位，仅对Velodyne LiDAR(lidar_type=2)生效

mapping:
  acc_cov: 0.1
  gyr_cov: 0.1
  b_acc_cov: 0.001
  b_gyr_cov: 0.001
  fov_degree: 360
  det_range: 200.0
  extrinsic_est_en: false      # true: enable the online estimation of IMU-LiDAR extrinsic
  # extrinsic_T: [ -0.0213 , -0.0172, 0.0362 ] # 万集雷达 参数
  extrinsic_T: [0.0 , 0.0 , 0.1] # 郑州列检
  extrinsic_R: [ 1, 0, 0,
                 0, 1, 0,
                 0, 0, 1 ]

publish:
  path_publish_en: false
  scan_publish_en: true       # false: close all the point cloud output
  scan_effect_pub_en: true    # true: publish the pointscloud of effect point
  dense_publish_en: false       # false: low down the points number in a global-frame point clouds scan.
  scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

path_save_en: true                 # 保存轨迹，用于精度计算和比较

pcd_save:
  pcd_save_en: false
  interval: -1                 # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

# feature_extract_enable: true
point_filter_num: 1
max_iteration: 5
filter_size_surf: 0.1
filter_size_map: 0.3
cube_side_length: 100000

ivox_grid_resolution: 0.3        # default=0.2
ivox_nearby_type: 18             # 6, 18, 26
esti_plane_threshold: 0.1        # default=0.1